services:
  - type: worker
    name: anime4u-telegram-storage-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: STORAGE_CHANNEL_ID
        sync: false
      - key: MAX_FILE_SIZE
        value: "2147483648"
      - key: AUTO_HLS
        value: "false"
      - key: TEMP_DIR
        value: "./downloads"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
